language: python
python:
  - "3.6"
  - "3.7.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
# command to run tests
script:
  - pytest wow_addon_manager/tests/test_config.py